# Generated by Django 2.1.7 on 2019-02-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('carrying', models.IntegerField()),
                ('owner', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('vendor_code', models.CharField(max_length=256)),
                ('expiration', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Consignment')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=32)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Store'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Product'),
        ),
    ]
