# Generated by Django 2.1.7 on 2019-02-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carrying',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(),
        ),
    ]
