# Generated by Django 2.1.7 on 2019-03-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20190302_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.Shipping'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.Store'),
        ),
    ]
