# Generated by Django 2.1.7 on 2019-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20190302_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='busy',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
