# Generated by Django 2.1.7 on 2019-03-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_car_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
