# Generated by Django 2.1.7 on 2019-03-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_shipping_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'машина', 'verbose_name_plural': 'машины'},
        ),
        migrations.AlterModelOptions(
            name='consignment',
            options={'verbose_name': 'партия товара', 'verbose_name_plural': 'партии товара'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'перевозка', 'verbose_name_plural': 'перевозки'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'склад', 'verbose_name_plural': 'склады'},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='busy',
            field=models.BooleanField(blank=True, default=False, verbose_name='занята'),
        ),
        migrations.AlterField(
            model_name='car',
            name='carrying',
            field=models.FloatField(verbose_name='грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(max_length=128, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='cost',
            field=models.FloatField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='manufacture_date',
            field=models.DateField(verbose_name='дата изготовления'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='quantity',
            field=models.IntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.Shipping', verbose_name='перевозится'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.Store', verbose_name='хранится в'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.FloatField(verbose_name='срок годности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=256, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(verbose_name='масса'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Car', verbose_name='машина'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Store', verbose_name='назначение'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='finished',
            field=models.BooleanField(blank=True, default=False, verbose_name='выполнена'),
        ),
        migrations.AlterField(
            model_name='store',
            name='capacity',
            field=models.IntegerField(verbose_name='вместимость'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=32, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.CharField(max_length=128, verbose_name='владелец'),
        ),
    ]
