# Generated by Django 2.1.7 on 2019-03-09 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_auto_20190309_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='выполнена'),
            preserve_default=False,
        ),
    ]
