# Generated by Django 2.1.7 on 2019-03-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_auto_20190309_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='выполнена'),
        ),
    ]
