# Generated by Django 2.1.7 on 2019-03-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_auto_20190309_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StorageCons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Shipping')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='storage',
        ),
        migrations.AddField(
            model_name='shippingcons',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Consignment'),
        ),
        migrations.AddField(
            model_name='shippingcons',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Shipping'),
        ),
    ]
