# Generated by Django 2.1.7 on 2019-03-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_auto_20190309_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingcons',
            options={'verbose_name': 'движение товара', 'verbose_name_plural': 'движения товара'},
        ),
        migrations.AlterModelOptions(
            name='storagecons',
            options={'verbose_name': 'хранение товара', 'verbose_name_plural': 'хранение товара'},
        ),
        migrations.AddField(
            model_name='shipping',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='store_app.Store', verbose_name='отправление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='store_app.Store', verbose_name='назначение'),
        ),
    ]
