# Generated by Django 2.1.7 on 2019-03-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_auto_20190310_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'заявка на перевозку',
                'verbose_name_plural': 'заявки на перевозку',
            },
        ),
        migrations.AddField(
            model_name='shipping',
            name='in_process',
            field=models.BooleanField(blank=True, default=False, verbose_name='выполняется'),
        ),
        migrations.AddField(
            model_name='bid',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Shipping', verbose_name='перевозка'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('product', 'shipping')},
        ),
    ]
