# Generated by Django 2.1.7 on 2019-03-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_auto_20190310_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='initial_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='изначальное количество'),
        ),
    ]
