# Generated by Django 2.1.7 on 2019-03-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_consignment_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcons',
            name='consignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_app.Consignment', verbose_name='партия'),
        ),
        migrations.AlterField(
            model_name='storagecons',
            name='consignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_app.Consignment', verbose_name='партия'),
        ),
    ]
