# Generated by Django 2.1.7 on 2019-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_auto_20190310_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='manufacture_date',
            field=models.DateTimeField(verbose_name='дата изготовления'),
        ),
    ]
