# Generated by Django 2.1.7 on 2019-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_auto_20190316_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='expired',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
