# Generated by Django 2.1.7 on 2019-03-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_consignment_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(blank=True, default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Car')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Store')),
            ],
            options={
                'verbose_name': 'Утилизация',
                'verbose_name_plural': 'Утилизационные перевозки',
            },
        ),
        migrations.AlterField(
            model_name='consignment',
            name='expired',
            field=models.BooleanField(blank=True, default=False, verbose_name='просрочен'),
        ),
    ]
